name: CI
on:
  push:
    branches: [master, development]
  pull_request:
    branches: [master, development]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: "14.15.4"
      - run: npm install
      - name: The eslint checking
        run: npm run lint:fix
        env:
          CI: true
